<?php
$Sayfa[0]="anasayfa.php";
$Sayfa[1]="tanitim.php";
$Sayfa[2]="duyurular.php";
$Sayfa[3]="haberler.php";
$Sayfa[4]="iletisim.php";
$Sayfa[5]="iletisimsonuc.php";
$Sayfa[6]="iletisimsonuctamam.php";
$Sayfa[7]="iletisimsonuchata.php";
$Sayfa[8]="iletisimsonuceksikalan.php";
$Sayfa[9]="destek.php";   
$Sayfa[10]="uyegiris.php";
$Sayfa[11]="uyegirissonuc.php";
$Sayfa[12]="uyegirissonuchata.php";
$Sayfa[13]="uyegirissonucyanlisbilgi.php";
$Sayfa[14]="uyegirissonuceksikalan.php";
$Sayfa[15]="sifremiunuttum.php";
$Sayfa[16]="sifremiunuttumsonuc.php";
$Sayfa[17]="kisiler.php";
$Sayfa[18]="yayinlar.php";
$Sayfa[19]="yayinlarsonuc.php";
$Sayfa[20]="projeler.php";
$Sayfa[21]="projelersonuc.php";
$Sayfa[22]="veriseti.php";
$Sayfa[23]="verisetisonuc.php";
?>